name: Format check

on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying

jobs:
  check:
    name: Format check
    runs-on: ubuntu-latest

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Formatting
        run: cargo fmt -- --check
